version: "3.7"

services:
  postgreSQL:
    image: postgres
    restart: always
    ports:
      - 8080:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    restart: always
    ports:
      - 3000:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "123456"]

  springboot-container:
    image: springboot-image
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgreSQL
      - redis
    restart: always
    ports:
      - 80:8080

volumes:
  postgres_data:
  redis_data:
