spring:
  application:
    name: wsd-web-crawling

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[default_batch_fetch_size]": 500
        "[highlight_sql]": true

logging:
  level:
    com:
      wsd:
        web:
          crawling: INFO
    org:
      springframework:
        security: INFO

jwt:
  access-secret: OtItGKqtKQiR1loQhhVkfZAnzMfoNmQgH9pEdKt4nSQ=
  refresh-secret: OtItGKqtKQiR1loQhhVkfZAnzMfoNmQgH9pEdKt4nSQ=
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
  authorization-header-access: AccessToken
  authorization-header-refresh: RefreshToken

allowed:
  origins: http://localhost:3000, http://localhost:5173
  methods: GET, POST, PUT, DELETE, OPTIONS

springdoc:
  swagger-ui:
    path: /docs