# Default Local application properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456