# Docker 컨테이너에서 실행할 때 사용할 설정 파일
spring:
  datasource:
    url: jdbc:postgresql://postgreSQL:5432/dev
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis
      port: 6379
      password: 123456
