spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saramin
#    url: jdbc:postgresql://localhost:13043/saramin
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    with-credentials: true
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG


